# Generated by Django 4.2.5 on 2023-09-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VisitedPlace', '0002_alter_visitedplace_visit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitedplace',
            name='visit_date',
        ),
    ]
